"""add_white_labeling_and_affiliation

Revision ID: 3bed83b18c3f
Revises: 47155a8d91e9
Create Date: 2026-05-21 12:10:57.170760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bed83b18c3f'
down_revision: Union[str, Sequence[str], None] = '47155a8d91e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type first
    sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='affiliationstatusenum').create(op.get_bind())
    op.add_column('hospitals', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('subdomain', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('white_label_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_hospitals_domain'), 'hospitals', ['domain'], unique=True)
    op.create_index(op.f('ix_hospitals_subdomain'), 'hospitals', ['subdomain'], unique=True)
    op.add_column('users', sa.Column('affiliation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='affiliationstatusenum'), server_default='APPROVED', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'affiliation_status')
    op.drop_index(op.f('ix_hospitals_subdomain'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_domain'), table_name='hospitals')
    op.drop_column('hospitals', 'white_label_config')
    op.drop_column('hospitals', 'subdomain')
    op.drop_column('hospitals', 'domain')
    op.execute('DROP TYPE affiliationstatusenum')
    # ### end Alembic commands ###
