"""core_db_expansion

Revision ID: 80bfb9544f9d
Revises: 1074b0bc6fbd
Create Date: 2026-04-26 19:52:45.741518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bfb9544f9d'
down_revision: Union[str, Sequence[str], None] = '1074b0bc6fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE appointmentstatusenum RENAME VALUE 'CANCELLED' TO 'RESCHEDULED'")
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('caregivers', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('post_call_summaries', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('post_call_summaries', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('video_sessions', sa.Column('actual_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_sessions', 'actual_duration_minutes')
    op.drop_column('post_call_summaries', 'summary')
    op.drop_column('post_call_summaries', 'transcript')
    op.drop_column('caregivers', 'avatar_url')
    op.drop_table('notifications')
    # ### end Alembic commands ###
