"""add_in_person_appointment_fields

Revision ID: e74120d1fb31
Revises: fab4a6eb523b
Create Date: 2026-06-22 09:54:16.478216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74120d1fb31'
down_revision: Union[str, Sequence[str], None] = 'fab4a6eb523b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('location_address', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('check_in_status', sa.String(length=50), nullable=True))
    op.add_column('doctor_availability', sa.Column('appointment_type', sa.Enum('VIDEO', 'FOLLOW_UP', 'NEW_PATIENT', 'IN_PERSON', name='appointmenttypeenum'), server_default='VIDEO', nullable=False))
    op.add_column('doctors', sa.Column('clinic_name', sa.String(length=255), nullable=True))
    op.add_column('doctors', sa.Column('clinic_address', sa.Text(), nullable=True))
    op.add_column('doctors', sa.Column('video_consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('doctors', sa.Column('in_person_consultation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('doctors', 'consultation_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('consultation_fee', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('doctors', 'in_person_consultation_fee')
    op.drop_column('doctors', 'video_consultation_fee')
    op.drop_column('doctors', 'clinic_address')
    op.drop_column('doctors', 'clinic_name')
    op.drop_column('doctor_availability', 'appointment_type')
    op.drop_column('appointments', 'check_in_status')
    op.drop_column('appointments', 'location_address')
    # ### end Alembic commands ###
